### ISSUE TITLE
Doesn't List term IDs besides the current term

### ISSUE THREAD

**Issue by Patronics** [bnjmnt4n/canvas-downloader#39]
It currently only lists the current/most recent term's term-id, while I'd like to download all previous terms as well. [another canvas export tool](https://github.com/davekats/canvas-student-data-export) is able to get info on previous terms as well, so it seems not to be an API limitation from Canvas.

**Comment by parth-io** [comment]
The reason for this is that we currently fetch from the `/api/v1/users/self/favorites/courses` endpoint, which only returns a list of active courses.

Fetching from `/api/v1/courses` will make previously-enrolled courses show up.

This should be an easy fix, but we would need to also consider improving the output printed to the terminal.

@Patronics in the meantime, you can change the URL endpoint in line 103 in `main.rs` and run `cargo build --release`.
